### ISSUE TITLE
Fix Console Errors

### ISSUE THREAD

**Issue by m1trix** [m1trix/steff-wedding#74]
On a freshly loaded `/dresses/{dress}` page, the following errors can be found in the console in Google Chrome:
```
popup.js:1 Uncaught TypeError: Cannot set properties of null (setting 'onkeyup')
    at popup.js:1:75743
(anonymous) @ popup.js:1
Show 1 more frame
Show less
popup.js:1 Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')
    at updateEmojis (popup.js:1:74545)
    at popup.js:1:75680
```
---
This needs to be investigated further, as the impact is currently unknown.

**Comment by m1trix** [comment]
Not reproducable
